//================This is split line================
// KEYWORD: COMPONENT NAME IS  Experiment18

// description:HelloWorld
// #define AOS_APP_EXPERIMENT18 0 // type: bool

// #if AOS_APP_EXPERIMENT18

// description:Firmware Version
// #define SYSINFO_APP_VERSION "app-1.0.0-20200214.140831" // type: string

// #endif

// description:CAN NOT BE MODIFIED
// #define AOS_CREATE_PROJECT 1 // type: bool

// description:CAN NOT BE MODIFIED
// #define AOS_BUILD_BOARD "esp32devkitc" // type: string

// description:CAN NOT BE MODIFIED
// #define AOS_BUILD_APP "Experiment18" // type: string

// description:CAN NOT BE MODIFIED
// #define AOS_SDK_PATH "" // type: string

// description:CAN NOT BE MODIFIED
// #define USER_APP_PATH "" // type: string

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) || ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((EN_BLE_HOST&&!bt_mesh_standalone_deploy)))

// #endif

// #if (((EN_BLE_HOST&&!bt_mesh_standalone_deploy)))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) || ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER))

// #endif

// #if ((ULOG_CONFIG_POP_FS) || (ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD))

// #endif

// #if ((ULOG_CONFIG_FS_FATFS_FLASH || ULOG_CONFIG_FS_FATFS_SD))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && SUPPORT_TLS || COAP_DTLS_SUPPORT) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && SUPPORT_TLS || COAP_DTLS_SUPPORT))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) || ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) || ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && USE_ITLS) || (((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD) && ENABLE_DYNAMIC_REGISTER) && USE_ITLS))

// #endif

// #if ((ULOG_CONFIG_FS_SPIFFS))

// #endif

// #if ((ULOG_CONFIG_UPLOAD || ULOG_CONFIG_POP_CLOUD))

// #endif

